<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowForge.Core\FlowForge.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
